### ISSUE TITLE
Wrong url for cargo-install in builder.toml

### ISSUE THREAD

**Issue by raffomartini** [paketo-community/rust#31]
The builder process was filing because rust-cargo couldn't be found on the repository.
`builder.toml` defines
```
uri = "docker://paketocommunity/rust-cargo:0.0.6"
```

it should be
```
uri = "docker://paketocommunity/cargo-install:0.0.6"
```

**Comment by dmikusa-pivotal** [comment]
Good catch, thanks! We have yet to automate the builder publishing, so it is not tested as much. Apologizes and hope to get that automated soon.
