### ISSUE TITLE
jam summarize no long works

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-community/rust#94]
Since `rust-dist` was moved off of `packit` and the `buildpack.toml` format changed in release v1.0.0, `jam summarize` no long plays nicely with the language family buildpack. Specifically, `jam summarize` fails in the [create release workflow.](https://github.com/paketo-community/rust/actions/runs/1225798554). This is because there is some disconnect in the format of the buildpack.toml and what versions of packit expect since[ jam v0.14.1 ](https://github.com/paketo-buildpacks/packit/releases/tag/v0.14.1) and on.

The recourse here is either to roll back to an older version of packit/jam (the v0.14.0 or before). Eventually, a fix for this issue in packit should come out (there is [an issue open](https://github.com/paketo-buildpacks/packit/issues/222) for this already), but in order to get releases created with the current automation, rolling back might be necessary.

**Comment by dmikusa-pivotal** [comment]
Pardon our dust :)  Doing a little bit of restructuring here.

I'm halfway through migrating things. The rust-dist & rustup CNBs are done. I have most of Cargo done, but need more time/testing before I push up those changes. After that, if this is still an issue I can circle back and take care of it as well.
